spring.application.name=authuser
server.port=8081

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ead_authuser
spring.datasource.username=postgres
spring.datasource.password=admin

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.show_sql=true